### PR TITLE
Add tests for ConfigValidator

### PR DESCRIPTION
**Pull request by husonghua**
Hey Sam, I have been using Lasso for a while now and think I should contribute somehow. I am adding ConfigValidator tests and hope that will check one box on your Issue #38.  I am relatively new to open source and let me know if something is not up to the standard. Thanks!

### CODE REVIEW

**Comment by Sammyjo20** [comment]
Hey @husonghua, thank you so much! 🙏 I've taken a look at your PR and it looks good so far, I noticed a couple of things that could be changed. 

Please could you remove test "it_throws_exception_when_storage_push_to_git_is_set" because this is legacy code, and Lasso no longer supports the "push to git" feature.

One other thing - please could you rename the last test from "final_test" to "it_throws_exception_when_public_path_is_inaccessible" 

Thanks!

**Comment by Sammyjo20** [comment]
Ah, just remembered the push_to_git message - please keep this in.

**Comment by husonghua** [comment]
Just fixed the test function name. I overlooked it when I rushed for the push yesterday.

I will try to help out with additional test coverage when I have some free time. Thanks!

**Comment by Sammyjo20** [comment]
Thank you for helping, husonghua

**Pull request merged**
