### PR TITLE
Remove composer.lock

### PR DESCRIPTION
**Pull request by mvdnbrk**
You should not commit your composer.lock file to the repository.

### CODE REVIEW

**Comment by Sammyjo20** [comment]
Brilliant, I didn't know this - thank you Mark!

**Comment by mvdnbrk** [comment]
👍

**Comment by Sammyjo20** [comment]
I've been Googling it a little, why is it good to remove the composer.lock for packages? When we work on big projects (e.g a Laravel app) we will include the composer.lock - is there a difference when it comes to composer packages?

**Comment by mvdnbrk** [comment]
Yes, when you are working on project you want to ensure you are installing the exact same dependencies to ensure the app is working as you would expect.

For packages it is more up the user land. Still you should take care of the `composer.json` file. That will tell another developer what you are requiring for your package to work.

**Pull request merged**
